syntax = "proto3";

package dsearch.query;

option java_package = "com.danieljhkim.dsearch.proto.query";
option java_multiple_files = true;
import "common/search_type.proto";
import "common/fusion_strategy.proto";

message QueryRequest {
  string query_string = 1;
  string shard_id = 2;
  int32 top_k = 3;
  int32 page = 4;
  int32 size = 5;
  dsearch.common.SearchType search_type = 6;
  dsearch.common.FusionStrategy fusion_strategy = 7;
}

message SearchHit {
  string doc_id = 1;
  double score = 2;
  string content = 3;
  string title = 4;
}

message QueryResponse {
  repeated SearchHit hits = 1;
  int64 total_hits = 2;
  int32 page = 3;
  int32 size = 4;
}

service QueryService {
  rpc Search(QueryRequest) returns (QueryResponse);
}