indexNodes:
  nodes:
    - id: "0"
      host: "localhost"
      port: 5000
    - id: "1"
      host: "localhost"
      port: 5001
  routingStrategy: "LEAST_LOADED"

queryNodes:
  nodes:
    - id: "0"
      host: "localhost"
      port: 6000
    - id: "1"
      host: "localhost"
      port: 6001
  routingStrategy: "ROUND_ROBIN"

ml:
  models:
    textEmbedding:
      url: "djl://ai.djl.huggingface.pytorch/sentence-transformers/all-MiniLM-L6-v2"
      engine: "PyTorch"
